[project]
name = 'bitvault'
description = 'Advanced sBTC Yield Farming & AMM Protocol'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'

[contracts.bitvault]
path = 'contracts/bitvault.clar'
clarity_version = 4
epoch = 'latest'

[contracts.sbtc-token-mock]
path = 'contracts/sbtc-token-mock.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
